language: node_js
node_js:
  - 10
  
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

install:
  - npm installinstall:
  - npm install -g gulp bower cordova ionic
  - npm install
  - bower update